// Two export shapes: Markdown for a file, and a compact block for the clipboard.
// The clipboard one exists so you can paste a clean computed summary into any
// assistant you like -- the app owns the numbers, the model owns the words.

import { fmtClock, fmtDuration, narrative, suggestion } from "./debrief.js";

const pct = (x) => `${Math.round(x * 100)}%`;

export function toMarkdown(a, notes = []) {
  const s = suggestion(a);
  const date = new Date(a.startMs).toLocaleDateString([], { weekday: "long", day: "numeric", month: "long", year: "numeric" });
  const L = [];
  L.push(`# Debrief — ${date}`);
  if (a.synthetic) L.push(`> Synthetic sample data, not a real recording.`);
  L.push("");
  L.push(narrative(a));
  L.push("");
  L.push(`## Numbers`);
  L.push(`| | |`);
  L.push(`|---|---|`);
  L.push(`| Recorded | ${fmtDuration(a.recordedMs)} |`);
  L.push(`| Readings | ${a.rows.toLocaleString()} (${pct(a.coverage)} usable) |`);
  L.push(`| Focus median | ${a.focus.p50.toFixed(3)} |`);
  L.push(`| Focus range (p10–p90) | ${a.focus.p10.toFixed(3)} – ${a.focus.p90.toFixed(3)} |`);
  L.push(`| Calm median | ${a.calm.p50.toFixed(3)} |`);
  for (const b of ["delta", "theta", "alpha", "beta", "gamma"]) {
    L.push(`| ${b} mean | ${a.bands[b].mean.toFixed(3)} |`);
  }
  if (a.peaks.length) {
    L.push("");
    L.push(`## Peaks`);
    a.peaks.forEach((p) => L.push(`- ${fmtClock(p.startMs)}–${fmtClock(p.endMs)} · ${fmtDuration(p.durationMs)} · mean ${p.meanValue.toFixed(2)}`));
  }
  if (a.slumps.length) {
    L.push("");
    L.push(`## Slumps`);
    a.slumps.forEach((p) => L.push(`- ${fmtClock(p.startMs)}–${fmtClock(p.endMs)} · ${fmtDuration(p.durationMs)} · low ${p.lowValue.toFixed(2)}`));
  }
  if (notes.length) {
    L.push("");
    L.push(`## Session notes`);
    notes.forEach((n) => L.push(`- ${fmtClock(n.epoch_ms)} — ${n.text}`));
  }
  if (s) {
    L.push("");
    L.push(`## Suggestion`);
    L.push(`**${s.headline}.** ${s.body}`);
  }
  L.push("");
  L.push(`---`);
  L.push(`Generated by Crown Debrief from ${a.rows.toLocaleString()} readings. Every figure above is computed from the CSV; no model wrote any of it.`);
  return L.join("\n");
}

/** Compact, labelled, and safe to paste anywhere. Derived numbers only — no raw EEG. */
export function toClipboardSummary(a, notes = []) {
  const L = [];
  L.push(`Neurosity Crown session summary${a.synthetic ? " (SYNTHETIC SAMPLE DATA)" : ""}`);
  L.push(`Date: ${new Date(a.startMs).toDateString()}  ${fmtClock(a.startMs)}–${fmtClock(a.endMs)}`);
  L.push(`Recorded: ${fmtDuration(a.recordedMs)} · ${a.rows} readings · ${pct(a.coverage)} usable signal`);
  L.push(``);
  L.push(`Focus (0-1, from gamma 30-44Hz): median ${a.focus.p50.toFixed(3)}, p10 ${a.focus.p10.toFixed(3)}, p90 ${a.focus.p90.toFixed(3)}`);
  L.push(`Calm  (0-1, from alpha 7.5-12.5Hz): median ${a.calm.p50.toFixed(3)}, p10 ${a.calm.p10.toFixed(3)}, p90 ${a.calm.p90.toFixed(3)}`);
  L.push(`Note: Neurosity documents that values above 0.3 are already significant.`);
  L.push(``);
  L.push(`Band means: ` + ["delta", "theta", "alpha", "beta", "gamma"].map((b) => `${b} ${a.bands[b].mean.toFixed(3)}`).join(", "));
  L.push(`Time in state: ` + Object.entries(a.timeInState).map(([k, v]) => `${k} ${pct(v.share)}`).join(", "));
  if (a.peaks.length) L.push(`Peaks: ` + a.peaks.map((p) => `${fmtClock(p.startMs)}-${fmtClock(p.endMs)} (${fmtDuration(p.durationMs)})`).join("; "));
  if (a.slumps.length) L.push(`Slumps: ` + a.slumps.map((p) => `${fmtClock(p.startMs)}-${fmtClock(p.endMs)} (${fmtDuration(p.durationMs)})`).join("; "));
  if (a.bestHour) L.push(`Best hour: ${String(a.bestHour.hour).padStart(2, "0")}:00 (mean focus ${a.bestHour.meanFocus.toFixed(3)})`);
  if (notes.length) {
    L.push(``);
    L.push(`What I was doing:`);
    notes.forEach((n) => L.push(`  ${fmtClock(n.epoch_ms)} — ${n.text}`));
  }
  return L.join("\n");
}
